# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Sauce Theme"
license = "MIT"
licenselink = "https://github.com/awsomsauce/hugo-theme-sauce/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/awsomsauce/hugo-theme-sauce"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.54.0"

[author]
  name = "Sanket Dasgupta"
  homepage = "https://sanketdg.github.io"
